%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [output1,output2,output3] = tbcenc_wrapper_fixpt(msg_in,intlv)
    fm = get_fimath();
    msg_in_in = fi( msg_in, 0, 1, 0, fm );
    intlv_in = fi( intlv, 0, 4, 0, fm );
    [output1_out,output2_out,output3_out] = tbcenc_fixpt( msg_in_in, intlv_in );
    output1 = output1_out;
    output2 = output2_out;
    output3 = output3_out;
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
